name: Clean Repository
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean all files except README.md
        run: |
          find . -type f ! -name 'README.md' ! -path './.git/*' -delete
          find . -type d -empty -delete

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Repository temizlendi" || exit 0
          git push