name: Clean Repository
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean all files except README.md and CNAME
        run: |
          find . -type f ! -name 'README.md' ! -name 'CNAME' ! -path './.git/*' -delete
          find . -type d -empty -delete

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Repository temizlendi" || exit 0
          git push