name: Extract Project
on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract zip and cleanup
        run: |
          unzip project.zip
          rm project.zip

      - name: Commit extracted files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Proje dosyaları açıldı" || exit 0
          git push